// Posting (a caterer's post with a generated JPEG, occasion + credits, tagged-in,
// edit, delete + storage cleanup) and a second listing in another vertical.
import { assert, eq, expectError, skip } from '../lib/harness.mjs'
import { solidJpeg } from '../lib/jpeg.mjs'

const listFolder = async (client, bucket, folder) => {
  const { data, error } = await client.storage.from(bucket).list(folder, { limit: 100 })
  if (error) throw error
  return (data || []).filter((f) => f.name && !f.name.startsWith('.'))
}

export const posting = {
  id: 'posting',
  title: 'Posting for a non-photo vertical',
  roles: ['caterer', 'clientA'],
  steps: [
    {
      name: 'caterer posts an album (JPEG, occasion, credit)',
      run: async (ctx) => {
        const { app, state } = ctx
        const me = await ctx.as('caterer')
        const listing = await app.portfolio.getMyProvider(me.uid, 'catering')
        assert(listing && listing.vertical === 'catering', 'caterer has no catering listing')
        const serviceIds = await app.portfolio.getProviderServiceIds(listing.id)
        const bytes = solidJpeg({ size: 32, gray: 170 })
        const file = new File([bytes], 'e2e-photo.jpg', { type: 'image/jpeg' })
        const display = { blob: new Blob([solidJpeg({ size: 16, gray: 170 })], { type: 'image/jpeg' }), width: 16, height: 16 }
        let progress = 0
        const albumId = await app.portfolio.postAlbum({
          userId: me.uid,
          providerId: listing.id,
          kind: 'album',
          title: ctx.tag('tasting menu'),
          caption: ctx.tag('generated by the e2e test'),
          location: 'Los Angeles, CA',
          shotOn: null,
          categoryId: serviceIds[0] || null,
          files: [{ file, display, settings: { body: 'e2e camera' } }],
          onProgress: (done) => (progress = done),
          occasion: 'birthday',
          credits: [{ providerId: state.photographerListing.id, role: 'Photographer' }],
        })
        ctx.cleanup.add('content', `delete post ${albumId.slice(0, 8)}`, async () => {
          await ctx.as('caterer')
          if (await app.portfolio.getAlbum(albumId)) await app.portfolio.deleteAlbum(albumId)
        })
        eq(progress, 1, 'onProgress photos done')
        state.post = { albumId, listing, uid: me.uid }
        return `album ${albumId.slice(0, 8)} on ${listing.display_name}`
      },
    },
    {
      name: 'public view: photo, occasion, credits',
      run: async (ctx) => {
        const { app, state } = ctx
        ctx.anon()
        const row = await app.portfolio.getAlbum(state.post.albumId)
        assert(row, 'signed-out visitors can\'t see the new post')
        eq(row.status, 'published', 'status')
        const v = app.portfolio.toViewerAlbum(row)
        eq(v.photos.length, 1, 'photos')
        eq(v.occasion?.slug, 'birthday', 'occasion')
        eq(v.credits.length, 1, 'credits')
        eq(v.credits[0].providerId, state.photographerListing.id, 'credited vendor')
        eq(v.credits[0].label, 'Photographer', 'credit role')
        eq(v.photos[0].exif?.body, 'e2e camera', 'camera settings saved')
        const res = await fetch(v.photos[0].src)
        eq(res.status, 200, 'public photo URL status')
        const got = new Uint8Array(await res.arrayBuffer())
        eq(got[0] === 0xff && got[1] === 0xd8, true, 'served bytes are a JPEG')
        state.post.src = v.photos[0].src
        return `photo served (${got.length} bytes), occasion ${v.occasion.name}, credit ${v.credits[0].name}`
      },
    },
    {
      name: 'credited vendor shows it under "Tagged in"',
      run: async (ctx) => {
        ctx.anon()
        const tagged = await ctx.app.portfolio.listTaggedAlbums(ctx.state.photographerListing.id)
        const hit = tagged.find((a) => a.id === ctx.state.post.albumId)
        assert(hit, 'post missing from listTaggedAlbums')
        eq(hit.by.id, ctx.state.post.listing.id, 'tagged-in "by"')
        return `${tagged.length} tagged post(s) for ${ctx.state.photographerListing.name}`
      },
    },
    {
      name: 'edit: title, occasion, credits',
      run: async (ctx) => {
        const { app, state } = ctx
        await ctx.as('caterer')
        const row = await app.portfolio.updateAlbum(state.post.albumId, { title: ctx.tag('tasting menu (edited)'), occasion: 'graduation', credits: [] })
        const v = app.portfolio.toViewerAlbum(row)
        eq(v.title, ctx.tag('tasting menu (edited)'), 'title')
        eq(v.occasion?.slug, 'graduation', 'occasion')
        eq(v.credits.length, 0, 'credits')
        ctx.anon()
        assert(!(await app.portfolio.listTaggedAlbums(state.photographerListing.id)).some((a) => a.id === state.post.albumId), 'still tagged after removing the credit')
        return 'edited; credit removed from "Tagged in"'
      },
    },
    {
      name: 'other users can\'t edit or delete it',
      soft: true,
      run: async (ctx) => {
        const { app, state } = ctx
        await ctx.as('clientA')
        await expectError(app.portfolio.updateAlbum(state.post.albumId, { title: 'hacked' }), /couldn.t be changed/i, 'client editing the post')
        await expectError(app.portfolio.deleteAlbum(state.post.albumId), /couldn.t be deleted/i, 'client deleting the post')
        return 'refused'
      },
    },
    {
      name: 'delete: row + both storage files',
      run: async (ctx) => {
        const { app, state } = ctx
        const me = await ctx.as('caterer')
        const folder = `${state.post.uid}/${state.post.albumId}`
        const before = (await listFolder(me.client, 'portfolio', folder)).length + (await listFolder(me.client, 'portfolio-originals', folder)).length
        eq(before, 2, 'files before delete (display + original)')
        const { filesLeft } = await app.portfolio.deleteAlbum(state.post.albumId)
        eq(filesLeft, 0, 'files Storage refused to delete')
        eq((await listFolder(me.client, 'portfolio', folder)).length, 0, 'portfolio files left')
        eq((await listFolder(me.client, 'portfolio-originals', folder)).length, 0, 'original files left')
        ctx.anon()
        eq(await app.portfolio.getAlbum(state.post.albumId), null, 'post after delete')
        // Informational only: a CDN may keep serving a cached copy for a while.
        const res = await fetch(state.post.src).catch(() => null)
        return `2 files removed; public URL now ${res ? res.status : 'unreachable'}${res?.ok ? ' (CDN cache)' : ''}`
      },
    },
  ],
}

// ---------------------------------------------------------------------------

export const listing = {
  id: 'listing',
  title: 'A second listing in another vertical',
  roles: ['caterer', 'clientA', 'clientB'],
  steps: [
    {
      name: 'becomeProvider in a concurrent vertical (max_concurrent)',
      run: async (ctx) => {
        const { app, state } = ctx
        const me = await ctx.as('caterer')
        const mine = await app.portfolio.getMyProviders(me.uid)
        const slug = `e2e-${ctx.roles.caterer.username.replace(/[^a-z0-9]+/gi, '-')}-2nd`.toLowerCase()
        let row = mine.find((p) => p.slug === slug)
        let vertical
        if (row) {
          vertical = row.vertical
          await me.client.from('providers').update({ status: 'active' }).eq('id', row.id) // reuse the one an earlier run made
        } else {
          const taken = new Set(mine.map((p) => p.vertical))
          const pick = app.verticals.VERTICALS.find((v) => v.concurrent && !taken.has(v.slug) && v.slug === 'rentals') || app.verticals.VERTICALS.find((v) => v.concurrent && !taken.has(v.slug))
          if (!pick) skip('the caterer already has a listing in every concurrent vertical')
          vertical = pick.slug
          const services = await app.portfolio.getServicesOf(vertical)
          row = await app.portfolio.becomeProvider({ displayName: `[e2e] ${ctx.roles.caterer.user.business || 'Vendor'} ${pick.name}`, slug, city: 'Los Angeles, CA', vertical, serviceIds: services.slice(0, 1).map((s) => s.id), bio: ctx.tag('second listing') })
        }
        ctx.cleanup.leave('providers', row.id)
        ctx.cleanup.add('listing', `hide listing ${slug}`, async () => {
          const c = await ctx.as('caterer')
          await c.client.from('providers').update({ status: 'draft' }).eq('id', row.id)
        })
        const fresh = await app.portfolio.getMyProvider(me.uid, vertical)
        eq(fresh.id, row.id, 'getMyProvider(uid, vertical)')
        eq(fresh.status, 'active', 'status')
        assert(fresh.max_concurrent > 1, `max_concurrent ${fresh.max_concurrent}, expected > 1 for ${vertical}`)
        state.second = { id: row.id, vertical, slug, maxConcurrent: fresh.max_concurrent }
        return `${vertical} listing ${slug} (max_concurrent ${fresh.max_concurrent}); caterer now has ${(await app.portfolio.getMyProviders(me.uid)).length} listings`
      },
    },
    {
      name: 'add a per-item package with min/max',
      run: async (ctx) => {
        const { app, state } = ctx
        await ctx.as('caterer')
        const services = await app.portfolio.getServicesOf(state.second.vertical)
        const pkg = await app.provider.createPackage(state.second.id, { name: '[e2e] Chair rental', categoryId: services[0]?.id ?? null, priceType: 'per_item', price: 8, depositPct: 25, attributes: { min_quantity: 10, max_quantity: 500 } })
        ctx.cleanup.add('content', `delete package ${pkg.id.slice(0, 8)}`, async () => {
          const c = await ctx.as('caterer')
          await c.client.from('packages').delete().eq('id', pkg.id)
        })
        eq(pkg.priceType, 'per_item', 'price type')
        eq(pkg.price, 8, 'price')
        eq(pkg.minQuantity, 10, 'min quantity')
        eq(pkg.maxQuantity, 500, 'max quantity')
        state.second.pkg = pkg
        return `"${pkg.name}" $8 each, 10-500`
      },
    },
    {
      name: 'public: listed in its vertical and in date search',
      run: async (ctx) => {
        const { app, state } = ctx
        ctx.anon()
        const list = await app.catalog.listProviders({ vertical: state.second.vertical })
        const p = list.find((x) => x.id === state.second.id)
        assert(p, `not in listProviders({ vertical: '${state.second.vertical}' })`)
        eq(p.startingPrice, 8, 'starting price')
        const day = ctx.dates.next()
        const found = await app.catalog.searchProviders({ vertical: state.second.vertical, dates: [day] })
        const hit = found.find((x) => x.id === state.second.id)
        assert(hit && hit.freeDates.includes(day), 'not free in date search')
        return `${list.length} ${state.second.vertical} listings; free on ${day}`
      },
    },
    {
      name: 'two overlapping bookings fit (capacity)',
      soft: true,
      run: async (ctx) => {
        const { app, state } = ctx
        const { rows, dates } = await ctx.book('clientA', { packageId: state.second.pkg.id, quantity: 20 }, { label: 'second listing 1' })
        eq(rows[0].total_cents, 16000, 'total for 20 items at $8')
        await ctx.as('clientB')
        const more = await app.bookings.requestBooking({ packageId: state.second.pkg.id, dates, startTime: '10:00', quantity: 12, notes: ctx.tag('second listing 2') })
        ctx.trackBooking('clientB', more[0].id, 'second listing 2')
        await app.bookings.cancelBooking(more[0].id)
        await ctx.as('clientA')
        await app.bookings.cancelBooking(rows[0].id)
        return `both fit on ${dates[0]}; cancelled`
      },
    },
    {
      name: 'hide the listing (draft) -> gone from public lists',
      run: async (ctx) => {
        const { app, state } = ctx
        const me = await ctx.as('caterer')
        const { error } = await me.client.from('providers').update({ status: 'draft' }).eq('id', state.second.id)
        if (error) throw error
        assert((await app.portfolio.getMyProviders(me.uid)).some((p) => p.id === state.second.id), 'owner lost sight of the draft')
        ctx.anon()
        assert(!(await app.catalog.listProviders({ vertical: state.second.vertical })).some((p) => p.id === state.second.id), 'draft still public')
        return 'draft; owner still sees it'
      },
    },
  ],
}
